name: nsf
module_path: rbi.models
class_name: InverseSplineAutoregressiveModel
params:
  shuffle: false
  num_transforms: 3
  count_bins: 12
  with_cache: false
  bound: 30
  hidden_dims:
    - 100
    - 100
  output_transform: biject_to

defaults:
  - embedding_net: identity