name: nsf
module_path: rbi.models
class_name: NeuralSplineFlow
params:
  randperm: true
  num_transforms: 3
  bins: 8
  hidden_dims:
    - 100
    - 100
  output_transform: biject_to

defaults:
  - embedding_net: identity