name: benchmark
id: null
idx: null
evaluate_metrics: True

run_train: True
run_eval: True
run_eval_rob: True
run_eval_approx: True

store_model: True
store_metrics: True
store_simulations: True

device: cpu 
verbose: True

data_path: /mnt/qb/macke/mgloeckler90/RBI_paper_final


hydra:
  run:
    dir: ${data_path}/outputs/${now:%Y-%m-%d}/${now:%H-%M-%S}

  sweep:
    dir: ${data_path}/outputs/${now:%Y-%m-%d}/${now:%H-%M-%S}

defaults:
  - _self_
  - model: gaussian 
  - task: gaussian_linear
  - train: fKL
  - defense: none
  - eval_rob: untargeted
  - eval_approx: all
  - eval_true: none
  - sweeper: none
  - launcher: slurm
  - partition: none
  - override hydra/launcher: submitit_slurm

seed: 0