class_name: NLLLoss
loss_module: rbi.loss
N_train: 10000
N_test: 10000
N_val: 512
batch_size: 512
shuffle: true
params:
  loss_fn_hyper_parameters: {}
  optimizer: Adam
  lr: 1e-3
  grad_clip_value: 75
  lr_scheduler: null
  lr_scheduler_kwargs:
    gamma: 0.99
  early_stopping: true
  patience: 10
  min_epochs: 5
  max_epochs: 300
  z_score_x: true
  train_in_unconstrained_space: true
  initialize_as_prior: false
  initialize_as_prior_rounds: 100