
attack_module: rbi.attacks
loss_module: rbi.loss
attack_class: IterativeRandomSearchAttack
attack_loss_fn: ForwardKLLoss
attack_mc_budget: 5
params: 
  ord: 2.
  mc_samples: 5
  eps_iter: 1000.
  nb_iter: 40
  clip_min: -1000
  clip_max: 1000
  contraction_factor: 1.3
  precision_factor: 0.01






