
attack_module: rbi.attacks.advertorch_attack
loss_module: rbi.loss
attack_class: L2PGDAttack
attack_loss_fn: ForwardKLLoss
attack_mc_budget: 5
params:
  eps_iter: "auto"
  nb_iter: 200
  clip_min: -1000
  clip_max: 1000







