defense_module: rbi.defenses.fisher_regularization
defense: EmpiricalFIMTraceRegularizer
params: 
  scale_eps_beta_by_std: true
  beta: 0.05
  ema_decay: 0.85
  reduce: mean
  clamp_val: null 
  grad_clamp_val: null