# @package _global_

sweeper:
  name: tpe
  objective: test_loss
  direction: minimize


defaults:
  - override /hydra/sweeper: optuna
  - override /hydra/sweeper/sampler: random

hydra:
  mode: MULTIRUN

  sweeper:
    sampler:
      _target_: optuna.samplers.RandomSampler
      seed: 0
    _target_: hydra_plugins.hydra_optuna_sweeper.optuna_sweeper.OptunaSweeper
    direction: ${sweeper.direction}
    study_name: rbibm_sweep
    n_trials: 500
    n_jobs: 500


store_model: false
store_metrics: false
store_simulations: false