
attack_module: rbi.attacks
loss_module: rbi.loss
attack_class: L1PGDAdamAttack
attack_loss_fn: ForwardKLLoss
attack_mc_budget: 1
params:
  eps_iter: "auto"
  nb_iter: 120
  clip_min: -1000
  clip_max: 1000







