# @package _global_

sweeper:
  name: tpe_multi_objective
  objective:
    - test_loss
    - metric_rob
  direction:
    - minimize
    - minimize

defaults:
  - override /hydra/sweeper: optuna
  - override /hydra/sweeper/sampler: motpe

hydra:
  mode: MULTIRUN

  sweeper:
    sampler:
      _target_: optuna.samplers.MOTPESampler
      seed: 0
      consider_prior: true
      prior_weight: 1.0
      consider_magic_clip:  true
      consider_endpoints:  false
      n_startup_trials:  200
      n_ehvi_candidates:  24
    _target_: hydra_plugins.hydra_optuna_sweeper.optuna_sweeper.OptunaSweeper
    direction: ${sweeper.direction}
    study_name: rbibm_sweep_multi_objective
    n_trials: 2000
    n_jobs: 20

store_model: false
store_metrics: false
store_simulations: false